server:
   port: 8083
   
logging:
  level:
    org.springframework.data.r2dbc: DEBUG

spring:
   r2dbc:
      url: r2dbc:h2:mem:///test?options=DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
      username: sa
      password:
   h2:
      console:
         enabled: true
         path: /h2-console
   security:
      ignored: "/actuator/**" 
            
keycloak:
   url: http://localhost:8080/
   realm: test
   jwk: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs