CREATE TABLE USER (
ID  INTEGER IDENTITY PRIMARY KEY,
NAME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(255) NOT NULL
);

INSERT INTO USER (ID, NAME,EMAIL) VALUES(1,'Test1','test@gmail.com');
INSERT INTO USER (ID, NAME,EMAIL) VALUES(2,'Test2','test2@gmail.com');
INSERT INTO USER (ID, NAME,EMAIL) VALUES(3,'Test3','test2@gmail.com');
INSERT INTO USER (ID, NAME,EMAIL) VALUES(4,'Test4','test2@gmail.com');
INSERT INTO USER (ID, NAME,EMAIL) VALUES(5,'Test5','test2@gmail.com');
INSERT INTO USER (ID, NAME,EMAIL) VALUES(6,'Test6','test2@gmail.com');
