server:
   port: 8008
   
spring:
   application:
      name: gateway-application
   cloud:
      gateway:
         default-filters:
         - name: AuthenticationGlobalFilter
         routes:
         - id: userinfo-route
           uri: http://localhost:8083/
           predicates:
           - Path=/api/**
                
management:
   endpoints:
      web:
         exposure:
            include: "*"
            
keycloak:
   url: http://localhost:8080
   realm: test
   jwk: ${keycloak.url}/auth/realms/${keycloak.realm}/protocol/openid-connect/certs